core/urls.py
from django.urls import path
from .views import signup, activate, temporary_index_redirect_to_focaccine, MyLoginView, UserUpdateView
# login_view, logout_view
from django.contrib.auth.views import LogoutView

urlpatterns = [
    # Account urls
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Edit account profile urls
    path('profile/', UserUpdateView.as_view(), name='user_profile'),

    # Index urls
    path('', temporary_index_redirect_to_focaccine, name='index'),
]

leonapp/urls.py
# from django.contrib import admin
from django.urls import path, include
# from django.contrib.auth.views import LogoutView

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
    # path('logout', LogoutView.as_view()),
    path('', include('core.urls')),
    path('focaccine/', include('focaccine.urls')),
    path('scan/', include('scan.urls')),
]

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Oauth(models.Model):
    type = models.CharField(max_length=20)
    grade = models.IntegerField()
    okey = models.CharField(max_length=32)
    expiration = models.DateTimeField()
    access_to = models.JSONField()
    commento = models.TextField()

    class Meta:
        managed = False
        db_table = 'OAuth'


class OauthMap(models.Model):
    oauth = models.CharField(db_column='OAuth', max_length=33)  # Field name made lowercase.
    email = models.CharField(max_length=80, blank=True, null=True)
    username = models.CharField(max_length=16, blank=True, null=True)
    password = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'OAuth_map'


class Accessi(models.Model):
    type = models.CharField(max_length=20)
    timestamp = models.DateTimeField()
    ip = models.CharField(max_length=42)
    website = models.CharField(max_length=40, blank=True, null=True)
    path = models.CharField(max_length=80)
    uniq = models.CharField(max_length=32)
    auth_key = models.CharField(max_length=80, blank=True, null=True)
    display_name = models.CharField(max_length=16, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'accessi'


class Acquisti(models.Model):
    user_id = models.IntegerField()
    date_purchased = models.DateTimeField()
    ticket_type = models.CharField(max_length=16)

    class Meta:
        managed = False
        db_table = 'acquisti'


class Consumazioni(models.Model):
    ticket_code = models.CharField(max_length=17)
    ticket_type = models.CharField(max_length=12)
    ticket_id = models.IntegerField()
    date_scanned = models.DateTimeField()
    scanner_id = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'consumazioni'


class Services(models.Model):
    tag = models.CharField(max_length=32)
    status = models.CharField(max_length=12)
    comment = models.TextField()
    last_ping = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'services'


class UserWhitelist(models.Model):
    email = models.CharField(unique=True, max_length=80)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    class_section = models.CharField(max_length=3)
    class_number = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'user_whitelist'


class Utenti(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    last_login = models.DateTimeField(blank=True, null=True)
    date_joined = models.DateTimeField()
    class_section = models.CharField(max_length=3)
    can_buy_tickets = models.IntegerField()
    username = models.CharField(unique=True, max_length=16)
    class_number = models.CharField(max_length=1)

    class Meta:
        managed = False
        db_table = 'utenti'

templates/acc_active_email copy.html
{#NO USAGE ANYMORE/YET#}

<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Conferma Email</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">
  /**
   * Google webfonts. Recommended to include the .woff version for cross-client compatibility.
   */
  @media screen {
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 400;
      src: local('Source Sans Pro Regular'), local('SourceSansPro-Regular'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/ODelI1aHBYDBqgeIAH2zlBM0YzuT7MdOe03otPbuUS0.woff) format('woff');
    }
    @font-face {
      font-family: 'Source Sans Pro';
      font-style: normal;
      font-weight: 700;
      src: local('Source Sans Pro Bold'), local('SourceSansPro-Bold'), url(https://fonts.gstatic.com/s/sourcesanspro/v10/toadOcfmlt9b38dHJxOBGFkQc6VGVFSmCnC_l7QZG60.woff) format('woff');
    }
  }
  /**
   * Avoid browser level font resizing.
   * 1. Windows Mobile
   * 2. iOS / OSX
   */
  body,
  table,
  td,
  a {
    -ms-text-size-adjust: 100%; /* 1 */
    -webkit-text-size-adjust: 100%; /* 2 */
  }
  /**
   * Remove extra space added to tables and cells in Outlook.
   */
  table,
  td {
    mso-table-rspace: 0pt;
    mso-table-lspace: 0pt;
  }
  /**
   * Better fluid images in Internet Explorer.
   */
  img {
    -ms-interpolation-mode: bicubic;
  }
  /**
   * Remove blue links for iOS devices.
   */
  a[x-apple-data-detectors] {
    font-family: inherit !important;
    font-size: inherit !important;
    font-weight: inherit !important;
    line-height: inherit !important;
    color: inherit !important;
    text-decoration: none !important;
  }
  /**
   * Fix centering issues in Android 4.4.
   */
  div[style*="margin: 16px 0;"] {
    margin: 0 !important;
  }
  body {
    width: 100% !important;
    height: 100% !important;
    padding: 0 !important;
    margin: 0 !important;
  }
  /**
   * Collapse table borders to avoid space between cells.
   */
  table {
    border-collapse: collapse !important;
  }
  a {
    color: #1a82e2;
  }
  img {
    height: auto;
    line-height: 100%;
    text-decoration: none;
    border: 0;
    outline: none;
  }
  </style>

</head>
<body style="background-color: #e9ecef;">

  <!-- start preheader -->
  <div class="preheader" style="display: none; max-width: 0; max-height: 0; overflow: hidden; font-size: 1px; line-height: 1px; color: #fff; opacity: 0;">
    A preheader is the short summary text that follows the subject line when an email is viewed in the inbox.
  </div>
  <!-- end preheader -->

  <!-- start body -->
  <table border="0" cellpadding="0" cellspacing="0" width="100%">

    <!-- start logo -->
    <!-- <tr>
      <td align="center" bgcolor="#e9ecef">
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="center" valign="top" style="padding: 36px 24px;">
              <a href="https://www.blogdesire.com" target="_blank" style="display: inline-block;">
                <img src="https://www.blogdesire.com/wp-content/uploads/2019/07/blogdesire-1.png" alt="Logo" border="0" width="48" style="display: block; width: 48px; max-width: 48px; min-width: 48px;">
              </a>
            </td>
          </tr>
        </table>
      </td>
    </tr> -->
    <!-- end logo -->

    <!-- start hero -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 36px 24px 0; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; border-top: 3px solid #d4dadf;">
              <h1 style="margin: 0; font-size: 32px; font-weight: 700; letter-spacing: -1px; line-height: 48px;">Conferma il tuo indirizzo email</h1>
            </td>
          </tr>
        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end hero -->

    <!-- start copy block -->
    <tr>
      <td align="center" bgcolor="#e9ecef">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">Tocca il pulsante in basso per confermare il tuo indirizzo email. Se non hai creato un account con <a href="https://www.leonapp.com">Leonapp</a>, puoi tranquillamente eliminare questa email.</p>
            </td>
          </tr>
          <!-- end copy -->

          <!-- start button -->
          <tr>
            <td align="left" bgcolor="#ffffff">
              <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                  <td align="center" bgcolor="#ffffff" style="padding: 12px;">
                    <table border="0" cellpadding="0" cellspacing="0">
                      <tr>
                        <td align="center" bgcolor="#1a82e2" style="border-radius: 6px;">
                          {% autoescape off %}
                          <a href="https://{{ domain }}{% url 'activate' uidb64=uid token=token %}" target="_blank" style="display: inline-block; padding: 16px 36px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; color: #ffffff; text-decoration: none; border-radius: 6px;">Attiva il tuo account</a>
                          {% endautoescape %}
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
          <!-- end button -->

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px;">
              <p style="margin: 0;">Se non funziona, copia e incolla il seguente link nel tuo browser:</p>
              {% autoescape off %}
              <p style="margin: 0;"><a href="https://{{ domain }}{% url 'activate' uidb64=uid token=token %}" target="_blank">https://{{ domain }}{% url 'activate' uidb64=uid token=token %}</a></p>
              {% endautoescape %}
            </td>
          </tr>
          <!-- end copy -->

          <!-- start copy -->
          <tr>
            <td align="left" bgcolor="#ffffff" style="padding: 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 24px; border-bottom: 3px solid #d4dadf">
              <p style="margin: 0;">Saluti,<br> Leonapp</p>
            </td>
          </tr>
          <!-- end copy -->

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end copy block -->

    <!-- start footer -->
    <tr>
      <td align="center" bgcolor="#e9ecef" style="padding: 24px;">
        <!--[if (gte mso 9)|(IE)]>
        <table align="center" border="0" cellpadding="0" cellspacing="0" width="600">
        <tr>
        <td align="center" valign="top" width="600">
        <![endif]-->
        <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">

          <!-- start permission -->
          <tr>
            <td align="center" bgcolor="#e9ecef" style="padding: 12px 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
              <p style="margin: 0;">You received this email because we received a request for [type_of_action] for your account. If you didn't request [type_of_action] you can safely delete this email.</p>
            </td>
          </tr>
          <!-- end permission -->

          <!-- start unsubscribe -->
          <tr>
            <td align="center" bgcolor="#e9ecef" style="padding: 12px 24px; font-family: 'Source Sans Pro', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 20px; color: #666;">
              <p style="margin: 0;">To stop receiving these emails, you can <a href="https://www.blogdesire.com" target="_blank">unsubscribe</a> at any time.</p>
              <p style="margin: 0;">Paste 1234 S. Broadway St. City, State 12345</p>
            </td>
          </tr>
          <!-- end unsubscribe -->

        </table>
        <!--[if (gte mso 9)|(IE)]>
        </td>
        </tr>
        </table>
        <![endif]-->
      </td>
    </tr>
    <!-- end footer -->

  </table>
  <!-- end body -->

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="it">

<head>
    <!-- <link rel="icon" type="image/x-icon" href="./src/img/logo.png"> -->
    <link rel="icon" type="image/x-icon" href="{% static 'core/logo/logo.png' %}">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Leonapp - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <meta name="description" content="L'app degli studenti del LeoneXIII è live!" />
    <meta property="og:title" content="Leonapp - LeoneXIII" />
    <meta property="og:image" content="{% static 'core/logo/logo.png' %}" />
    {% block css %}{% endblock %}
</head>

<body>

    <!--navigation-->
    <nav class="navbar py-4">
        <div class="container is-fluid">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'index' %}">
                    <img class="image" src="{% static 'core/logo/logo_text.png' %}" alt="" width="96px">
                </a>
                <a class="navbar-burger" role="button" data-target="navMenu" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{% url 'focaccine' %}">Home</a>
                    <a class="navbar-item" href="{% url 'ticket-history' %}">Biglietti</a>
                    <a class="navbar-item" href="{% url 'user_profile' %}">Profilo</a>
                    <!-- Other navbar items -->
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-light" href="{% url 'logout' %}">
                                Logout
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    


    <!--breadcrumbs-->
    <!-- <div class="section pt-4 pb-0">
        <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul class="container">
                <li>
                    <a class="has-text-grey is-size-7-mobile">Starbucks Coffee</a>
                </li>
                <li><a class="has-text-grey is-size-7-mobile">Shop</a></li>
                <li class="is-active">
                    <a class="is-size-7-mobile">Mocha Cookie Crumble Frappuccino</a>
                </li>
            </ul>
        </nav>
    </div> -->

    {% block content %}
    {% endblock %}

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            // Get all "navbar-burger" elements
            const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
    
            // Check if there are any navbar burgers
            if ($navbarBurgers.length > 0) {
                // Add a click event on each of them
                $navbarBurgers.forEach(el => {
                    el.addEventListener('click', () => {
                        // Get the target from the "data-target" attribute
                        const target = el.dataset.target;
                        const $target = document.getElementById(target);
    
                        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                        el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');
                    });
                });
            }
        });
    </script>
    
    

    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/index.html
{#NO USAGE ANYMORE/YET#}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="icon" type="image/x-icon" href="{% static 'core/logo/logo.png' %}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Leonapp - Accedi</title>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;500;700&display=swap" rel="stylesheet"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <meta name="description" content="L'app degli studenti del LeoneXIII è live!" />
    <meta property="og:title" content="Leonapp - LeoneXIII" />
    <meta property="og:image" content="{% static 'core/logo/logo.png' %}" />
</head>
<body>
  <section class="container">
    <div class="columns is-multiline">
      <div class="column is-8 is-offset-2 register">
        <div class="columns">
          <div class="column left">
            <h1 class="title is-1">Leonapp</h1>
            <h2 class="subtitle colored is-4">L'app degli studenti del Leone XIII.</h2>
            <p>
              Leonapp inizia il suo viaggio come una semplice soluzione per vendere le focaccine durante l'intervallo, 
              ma mira ad andare ben oltre le focaccine. 
              Leonapp è in continuo sviluppo per diventare il cuore pulsante della comunità leoniana.
            </p>
          </div>
          <div class="column right has-text-centered">
            <h1 class="title is-4">Accedi</h1>
            <p class="description">Attualmente, puoi accedere solo se sei un partecipante della 
              versione Beta di LEONAPP</p>
            <form method="post">
              {% csrf_token %}
              <div class="field">
                <div class="control">
                  <input class="input is-medium" type="email" placeholder="Email" id="id_email" name="email" required>
                </div>
              </div>

              <div class="field">
                <div class="control">
                  <input class="input is-medium" type="password" placeholder="Password" id="id_password" name="password" required>
                </div>
                {% if error_message %}
                <p class="help is-danger">{{ error_message }}</p>
                {% endif %}
              </div>
              <button class="button is-block is-primary is-fullwidth is-medium" type="submit">Accedi</button>
              <br />
              <small><em>Non hai un account? <a href="{% url 'signup' %}">Registrati</a></em></small>
            </form>
          </div>
        </div>
      </div>
      <div class="column is-8 is-offset-2">
        <br>
        <nav class="level">
          <div class="level-left">
            <div class="level-item">
              <!-- <span class="icon">
                <i class="fab fa-twitter"></i>
              </span> &emsp;
              <span class="icon">
                <i class="fab fa-facebook"></i>
              </span> &emsp; -->
              <a href="https://www.instagram.com/lindniele"><span class="icon">
                <i class="fab fa-instagram"></i>
              </span></a> &emsp;
              <a href="https://www.instagram.com/niccolo_pagano"><span class="icon">
                <i class="fab fa-instagram"></i>
              </span></a> &emsp;
              <a href="https://github.com/leonapp-project/"><span class="icon">
                <i class="fab fa-github"></i>
              </span></a> &emsp;
              <!-- <span class="icon">
                <i class="fas fa-envelope"></i>
              </span> -->
            </div>
          </div>
          <div class="level-right">
            <small class="level-item" style="color: var(--textLight)">
              Tutti i diritti riservati &copy; LEONAPP
            </small>
          </div>
        </nav>
      </div>
    </div>
  </section>
</body>
<style>
  :root {
    --brandColor: hsl(166, 67%, 51%);
    --background: rgb(247, 247, 247);
    --textDark: hsla(0, 0%, 0%, 0.66);
    --textLight: hsla(0, 0%, 0%, 0.33);
  }

  body {
    background: var(--background);
    height: 100vh;
    color: var(--textDark);
  }

  .field:not(:last-child) {
    margin-bottom: 1rem;
  }

  .register {
    margin-top: 10rem;
    background: white;
    border-radius: 10px;
  }

  .left,
  .right {
    padding: 4.5rem;
  }

  .left {
    border-right: 5px solid var(--background);
  }

  .left .title {
    font-weight: 800;
    letter-spacing: -2px;
  }

  .left .colored {
    color: var(--brandColor);
    font-weight: 500;
    margin-top: 1rem !important;
    letter-spacing: -1px;
  }

  .left p {
    color: var(--textLight);
    font-size: 1.15rem;
  }

  .right .title {
    font-weight: 800;
    letter-spacing: -1px;
  }

  .right .description {
    margin-top: 1rem;
    margin-bottom: 1rem !important;
    color: var(--textLight);
    font-size: 1.15rem;
  }

  .right small {
    color: var(--textLight);
  }

  input {
    font-size: 1rem;
  }

  input:focus {
    border-color: var(--brandColor) !important;
    box-shadow: 0 0 0 1px var(--brandColor) !important;
  }

  .fab,
  .fas {
    color: var(--textLight);
    margin-right: 1rem;
  }

</style>
</html>

templates/profile.html
<!-- profile.html -->

{% extends 'base.html' %}

{% block title %}Profilo{% endblock %}

{% block css %}
<style>
    :root {
      --brandColor: hsl(166, 67%, 51%);
      /* --background: rgb(247, 247, 247); */
      --textDark: hsla(0, 0%, 0%, 0.66);
      --textLight: hsla(0, 0%, 0%, 0.33);
    }

    body {
      background: var(--background);
      height: 100vh;
      color: var(--textDark);
    }

    .field:not(:last-child) {
      margin-bottom: 1rem;
    }

    /* .register {
      margin-top: 10rem;
      background: white;
      border-radius: 10px;
    } */

    .left,
    .right {
      padding: 4.5rem;
    }

    /* left is not used in profile.html, because the css style is borrowed from login.html and signup.html*/
    .left {
      border-right: 5px solid var(--background);
    }

    .left .title {
      font-weight: 800;
      letter-spacing: -2px;
    }

    .left .colored {
      color: var(--brandColor);
      font-weight: 500;
      margin-top: 1rem !important;
      letter-spacing: -1px;
    }

    .left p {
      color: var(--textLight);
      font-size: 1.15rem;
    }

    .right .title {
      font-weight: 800;
      letter-spacing: -1px;
    }

    .right .description {
      margin-top: 1rem;
      margin-bottom: 1rem !important;
      color: var(--textLight);
      font-size: 1.15rem;
    }

    .right small {
      color: var(--textLight);
    }

    input {
      font-size: 1rem;
    }

    input:focus {
      border-color: var(--brandColor) !important;
      box-shadow: 0 0 0 1px var(--brandColor) !important;
    }

    .fab,
    .fas {
      color: var(--textLight);
      margin-right: 1rem;
    }


    /* New style */
    .label {
        color: var(--textDark);
        font-weight: 700;
        margin-bottom: 0.5rem; /* Ensure spacing between label and input */
    }
</style>
{% endblock %}

{% block content %}
<!-- <h2>User Profile</h2>
<h2>User Profile</h2>
<div class="user-info">
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Class: {{ class_number_display }} {{ class_section_display }}</p>
</div>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
</form> -->

<section class="container">
  <div class="columns is-multiline">
      <!-- <div class="column is-8 is-offset-2 register"> -->
      <div class="column is-8 is-offset-2">
          <div class="column right">
              <h1 class="title is-1">Your Profile</h1>
              <p class="description">View and update your profile details.</p>

              {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <p class="{% if message.tags %}{{ message.tags }}{% endif %} help is-success">{{ message }}</p>
                {% endfor %}
              </ul>
              {% endif %}

              {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                      <p class="help is-danger">{{ error }}</p>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'user_profile' %}">
                  {% csrf_token %}
                  <!-- Username -->
                  <div class="field">
                    <label class="label" for="id_username">Username</label>
                    <div class="control">
                        <input class="input is-medium {% if form.username.errors %}is-danger{% endif %}" 
                               type="text" name="username" id="id_username" 
                               placeholder="Username" value="{{ form.username.value|default_if_none:'' }}" required>
                        {% if form.username.errors %}
                            {% for error in form.username.errors %}
                                <p class="help is-danger">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                  <!-- {{ form.as_p }} -->

                  <!-- First Name -->
                  <div class="field">
                      <label class="label">First Name</label>
                      <div class="control">
                          <input class="input is-medium" type="text" placeholder="First Name" value="{{ user.first_name }}" disabled>
                      </div>
                  </div>

                  <!-- Last Name -->
                  <div class="field">
                      <label class="label">Last Name</label>
                      <div class="control">
                          <input class="input is-medium" type="text" placeholder="Last Name" value="{{ user.last_name }}" disabled>
                      </div>
                  </div>

                  <!-- Email -->
                  <div class="field">
                      <label class="label">Email</label>
                      <div class="control">
                          <input class="input is-medium" type="email" placeholder="Email" value="{{ user.email }}" disabled>
                      </div>
                  </div>

                  <!-- Class -->
                  <div class="field">
                      <label class="label">Class</label>
                      <div class="control">
                          <input class="input is-medium" type="text" placeholder="Class" value="{{ user.get_class_number_display }} {{ user.get_class_section_display }}" disabled>
                      </div>
                  </div>

                  <button class="button is-block is-primary is-fullwidth is-medium" id="update-button" disabled>Update</button>

                  <br>
                  <small><em>Please contact support to change other profile details.</em></small>
              </form>
          </div>
      </div>
  </div>
</section>


{% endblock %}


{% block javascript %}
<script>
  document.addEventListener('DOMContentLoaded', () => {
    // Select the username input by id
    const usernameInput = document.getElementById('id_username');
    const updateButton = document.getElementById('update-button');

    // Enable the update button if there's a change in the input value
    usernameInput.addEventListener('input', () => {
      const initialValue = "{{ user.username|default_if_none:'' }}";
      updateButton.disabled = usernameInput.value === initialValue || !usernameInput.value.trim();
    });

    // Call the event listener function on page load to handle pre-filled values
    usernameInput.dispatchEvent(new Event('input'));
  });
</script>
{% endblock %}